<a href="https://colab.research.google.com/github/Saquib0001/MLQuest-Basic-/blob/main/2_Numpy_learn_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy - Numerical Python

Advantages of Numpy Arrays:

1.Allows several Mathematical Operations

2.Faster operation


In [ ]:
import numpy as np

List vs Numpy - Time Taken

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.0009753240000005547


In [ ]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - start_time)

0.0014002440000000504


In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0013110489999998975


In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0007682080000002145


In [ ]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)  # nd -> n dimension

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating a 1 dimension array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape #  It gives information about row and column

(4,)

In [ ]:
b = np.array([(1,2,3,4) , (5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2.5,3,4),(5,6,7,8)] , dtype = float)
print(c)

[[1.  2.5 3.  4. ]
 [5.  6.  7.  8. ]]


In [ ]:
# create a numpy array of Zeros
x = np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of a particular value
z = np.full((5,4) , 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# create an identitiy matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# create a numpy array with random values
b = np.random.random((3,3))
print(b)

[[0.55594484 0.00242804 0.67113531]
 [0.76044868 0.1463558  0.53582526]
 [0.17971203 0.87563203 0.8088925 ]]


In [ ]:
# random integer values array within a specific range
c = np.random.randint(5,50,(4,4))
print(c)

[[43 46 27 48]
 [27 46 12 43]
 [12 13 21 39]
 [16 18 40 28]]


In [ ]:
# array of evenly spaced values --> specifying the step
e = np.arange(5,20,2)
print(e)

[ 5  7  9 11 13 15 17 19]


In [ ]:
# Convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(4,4))
d = np.random.randint(1,4,5)
print(c)
print(d)

[[58 52 65 88]
 [10 45 23 45]
 [76 10 56 33]
 [51 77 83 66]]
[3 3 2 1 2]


In [ ]:
# array dimension
print(c.shape)
print(d.shape)

(4, 4)
(5,)


In [ ]:
# number of dimensions
print(c.ndim)
print(d.ndim)

2
1


In [ ]:
# number of elements in an array
print(c.size)
print(d.size)

16
5


In [ ]:
#cheking the data type of the values in the array
print(c.dtype)
print(d.dtype)

int64
int64


Mathematical operation on a np array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)  #concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)

[[6 5 3]
 [9 8 7]
 [3 3 7]]
[[16 10 15]
 [16 17 15]
 [11 14 10]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[22 15 18]
 [25 25 22]
 [14 17 17]]
[[-10  -5 -12]
 [ -7  -9  -8]
 [ -8 -11  -3]]
[[ 96  50  45]
 [144 136 105]
 [ 33  42  70]]
[[0.375      0.5        0.2       ]
 [0.5625     0.47058824 0.46666667]
 [0.27272727 0.21428571 0.7       ]]


In [ ]:
a = np.random.randint(0,20,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[ 2 10  8]
 [18  5  5]
 [ 2 13 12]]
[[18 14 19]
 [16 19 12]
 [15 17 19]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[20 24 27]
 [34 24 17]
 [17 30 31]]
[[-16  -4 -11]
 [  2 -14  -7]
 [-13  -4  -7]]
[[ 36 140 152]
 [288  95  60]
 [ 30 221 228]]
[[0.11111111 0.71428571 0.42105263]
 [1.125      0.26315789 0.41666667]
 [0.13333333 0.76470588 0.63157895]]


Array Manipulation

In [ ]:
array = np.random.randint(0,20,(2,3))
print(array)
print(array.shape)

[[17 13 13]
 [ 9  0  3]]
(2, 3)


In [ ]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)


[[17  9]
 [13  0]
 [13  3]]
(3, 2)


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 6 7]
 [0 1 3]]
(2, 3)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[7 0]
 [6 1]
 [7 3]]
(3, 2)


In [ ]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 1 4]
 [6 2 4]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[8 1]
 [4 6]
 [2 4]]
(3, 2)
